FROM ruby:2.5-alpine

RUN apk update && apk add build-base nodejs postgresql-dev

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install --binstubs

COPY . .

EXPOSE 3000

LABEL maintainer="Nick Janetakis <nick.janetakis@gmail.com>"

CMD puma -p 28080 cable/config.ru
