sudo: required
services: 
  - docker

before_install:
  - docker build -t mrdr/atwo-react-2 -f ./atwo-react-2/Dockerfile.dev ./atwo-react-2
  - docker-compose up -d
  - docker-compose exec website rails db:reset
  - docker-compose exec website rails db:migrate

script:
  - docker run -e CI=true mrdr/atwo-react-2 npm test
  - docker-compose run website rspec

after_success:
  - docker-compose down

  - docker build -t mrdr/atwo-nginx -f ./atwo-nginx/Dockerfile.dev ./atwo-nginx
  - docker build -t mrdr/atwo-react-2 ./atwo-react-2
  - docker build -t mrdr/atwo-rails ./atwo-rails
  - docker build -t mrdr/atwo-sidekiq -f ./atwo-rails/Dockerfile.sidekiq ./atwo-rails
  - docker build -t mrdr/atwo-cable -f ./atwo-rails/Dockerfile.cable ./atwo-rails

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mrdr/atwo-nginx
  - docker push mrdr/atwo-react-2 
  - docker push mrdr/atwo-rails 
  - docker push mrdr/atwo-sidekiq 
  - docker push mrdr/atwo-cable 