version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - ./atwo-rails/.env

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: ./atwo-rails
      dockerfile: Dockerfile
    expose:
      - '3000'
    volumes:
      - './atwo-rails/:/app'
    env_file:
      - ./atwo-rails/.env

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: ./atwo-rails
      dockerfile: Dockerfile.sidekiq
    volumes:
      - './atwo-rails/:/app'
    env_file:
      - ./atwo-rails/.env

  cable:
    depends_on:
      - 'redis'
    build:
      context: ./atwo-rails
      dockerfile: Dockerfile.cable
    ports:
      - '28080:28080'
    volumes:
      - './atwo-rails/:/app'
    env_file:
      - ./atwo-rails/.env

  frontend:
    build:
      context: ./atwo-react-2
      dockerfile: Dockerfile
    expose:
      - '3001'
    volumes:
      - ./atwo-react-2:/app

  nginx:
    restart: always
    build:
      context: ./atwo-nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3002:80'
    depends_on:
      - website
      - frontend
    volumes:
      - './atwo-nginx/default.conf:/etc/nginx/conf.d/default.conf'

volumes:
  redis:
  postgres:
